### ISSUE TITLE
'fetch' is undefined (IE 11)

### ISSUE THREAD

**Issue by willwade** [AceCentre/nhs-service-finder#4]
Getting an annoying error on Internet Explorer 11 on Windows. When entering a postcode and submitting you get a javascript error 'Fetch' is undefined. It still does the search and works fine except this.

**Comment by hosseinamin** [comment]
Did test with
```
IE version
Microsoft Edge 41.16299
```

Please check your IE's version at settings. Does it show the error for a specific input?
Screen-shot with console (f12) on can help.

**Comment by willwade** [comment]
IE 11
(Not Edge)

Happens on every postcode input. 
See this: https://www.dropbox.com/s/mcoo0z44edey4kj/ServicefinderError.mov?dl=0

**Comment by hosseinamin** [comment]
@willwade Fixed
