### ISSUE TITLE
Hugo bug

### ISSUE THREAD

**Issue by willwade** [AceCentre/nhs-service-finder#6]
see https://discourse.gohugo.io/t/fatal-error-concurrent-map-iteration-and-map-write/14699

And follow it down to https://discourse.gohugo.io/t/fatal-error-concurrent-map-iteration-and-map-write/14699/9?u=willwade :)

**Comment by hosseinamin** [comment]
@willwade Good to know. I ran to this issue too. parallel processing issues are hard to catch.
